# eksisozluk/eksisozluk

language: node_js
node_js:
  - '4' #Â LTS
  - '6' # Latest
  - '10'

sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq update 
  - npm install -g npm
  - npm install -g xo

script: 
  - npm test
